// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GooglePlayConstants
{
        public const string achievement_1000_score = "CgkIs4Ls1K8dEAIQCw"; // <GPGSID>
        public const string leaderboard_highest_score = "CgkIs4Ls1K8dEAIQFQ"; // <GPGSID>
        public const string achievement_100_score_without_hit = "CgkIs4Ls1K8dEAIQEQ"; // <GPGSID>
        public const string achievement_50_rounds = "CgkIs4Ls1K8dEAIQAg"; // <GPGSID>
        public const string achievement_20_score = "CgkIs4Ls1K8dEAIQBg"; // <GPGSID>
        public const string achievement_100_rounds = "CgkIs4Ls1K8dEAIQAw"; // <GPGSID>
        public const string achievement_50_shields = "CgkIs4Ls1K8dEAIQDA"; // <GPGSID>
        public const string achievement_50_score_without_hit = "CgkIs4Ls1K8dEAIQEA"; // <GPGSID>
        public const string achievement_500_score_without_hit = "CgkIs4Ls1K8dEAIQEw"; // <GPGSID>
        public const string achievement_50_score = "CgkIs4Ls1K8dEAIQBw"; // <GPGSID>
        public const string achievement_1000_rounds = "CgkIs4Ls1K8dEAIQBQ"; // <GPGSID>
        public const string achievement_500_rounds = "CgkIs4Ls1K8dEAIQBA"; // <GPGSID>
        public const string achievement_get_set_go = "CgkIs4Ls1K8dEAIQAQ"; // <GPGSID>
        public const string achievement_100_score = "CgkIs4Ls1K8dEAIQCA"; // <GPGSID>
        public const string achievement_250_score_without_hit = "CgkIs4Ls1K8dEAIQEg"; // <GPGSID>
        public const string achievement_500_shields = "CgkIs4Ls1K8dEAIQDg"; // <GPGSID>
        public const string achievement_250_score = "CgkIs4Ls1K8dEAIQCQ"; // <GPGSID>
        public const string achievement_100_shields = "CgkIs4Ls1K8dEAIQDQ"; // <GPGSID>
        public const string achievement_25_score_without_hit = "CgkIs4Ls1K8dEAIQDw"; // <GPGSID>
        public const string achievement_1000_score_without_hit = "CgkIs4Ls1K8dEAIQFA"; // <GPGSID>
        public const string achievement_500_score = "CgkIs4Ls1K8dEAIQCg"; // <GPGSID>

}

